#https://docs.wandb.ai/guides/sweeps/quickstart
program: sweep.py
method: bayes
project: radio_sunburst_detection
metric:
  goal: maximize
  name: val_recall
parameters:
  encoder_filters:
    values: [32, 64, 96, 128]
  encoder_kernel_size: 
    values: [3, 5]
  encoder_l1:
    min: 0.00001
    max: 0.01
  weight_initialization:
    values: ['glorot_uniform', 'he_normal']
  dropout:
    min: 0.0
    max: 0.5
  optimizer:
    values: ['adam', 'sgd', 'rmsprop']
  batch_size: 
    min: 32
    max: 512
  learning_rate:
    min: 0.0001
    max: 0.1
  num_dense_layers:
    values: [1, 2, 3]
  neurons_dense_layer:
    values: [64, 32, 16]



command:
  - ${interpreter}
  - ${program}
  - "--config_name"
  - "sweep" #Insert your model here (do not push it, adapt it each time.)