model_params:
  input_shape: [256, 256, 1]
  encoder_filters: 32
  encoder_kernel_size: 3
  encoder_l1: 0.00001
  weight_initialization: 'he_normal'
  num_hidden_layers: 2
  dropout: 0.1
  optimizer: 'adam'
  learning_rate: 0.001
  num_dense_layers: 2
  neurons_dense_layer: 64

model: autoencoder
batch_size: 128
epochs: 10
burst_frac: 0.1
instrument_to_use: [
    "australia_assa_02"
]