input_shape: [256, 256, 1]
l1: 0.00985604785523802
dropout: 0.15886306060207622
weight_initialization: 'he_normal'
learning_rate: 0.0685625334547779
last_layers_to_train: 3
elim_wrong_channels: False
epochs: 30
model: transfer
base_model_name: EfficientNetV2L
batch_size: 128
burst_frac: 0.1
sort_by_time: False
train_size: 0.7
instrument_to_use: [
    "australia_assa_02"
]