input_shape: [256, 256, 3]
l1: 0.00001
dropout: 0.2
weight_initialization: 'he_normal'
learning_rate: 0.001
last_layers_to_train: 2
elim_wrong_channels: False
epochs: 30
model: transfer
batch_size: 64
burst_frac: 0.5
instrument_to_use: [
    "australia_assa_02",
    "swiss_landschlacht_01",
    "alaska_haarp_62",
]