input_shape: [256, 256, 1]
l1: 0.00001
dropout: 0.2
weight_initialization: 'he_normal'
learning_rate: 0.001
last_layers_to_train: 2
elim_wrong_channels: False
epochs: 30
model: transfer
base_model_name: EfficientNetV2L
batch_size: 128
burst_frac: 0.5

burst_frac: 0.1

instrument_to_use: [
    "australia_assa_02",
    "swiss_landschlacht_01",
    "alaska_haarp_62",
]