input_shape: [256, 256, 1]
l1: 0.001696829726988035
dropout: 0.4254767190139672
weight_initialization: 'he_normal'
learning_rate: 0.0029465617656424083
last_layers_to_train: 3
elim_wrong_channels: False
epochs: 30
model: transfer
base_model_name: EfficientNetV2L
batch_size: 128
burst_frac: 0.5

burst_frac: 0.1

instrument_to_use: [
    "australia_assa_02"
]